// <auto-generated />
using System;
using AbnNotifier.Data.Notifier;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AbnNotifier.Migrations
{
    [DbContext(typeof(AbnNotifierDbContext))]
    [Migration("20190322133516_Update Sent Nots")]
    partial class UpdateSentNots
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AbnNotifier.Data.Notifier.Models.EmailSmsSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Data");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<int>("Key");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("EmailSmsSettings");
                });

            modelBuilder.Entity("AbnNotifier.Data.Notifier.Models.SentNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Content");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<int>("Department");

                    b.Property<string>("EmpNo");

                    b.Property<int>("Event");

                    b.Property<string>("Response");

                    b.Property<int>("Status");

                    b.Property<bool>("Success");

                    b.Property<string>("Supervisor");

                    b.Property<int>("UniIntId");

                    b.Property<string>("UniStrId");

                    b.HasKey("Id");

                    b.ToTable("SentNotifications");
                });

            modelBuilder.Entity("AbnNotifier.Data.Notifier.Models.Supervisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<int>("Department");

                    b.Property<string>("EmpNo");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Supervisors");
                });
#pragma warning restore 612, 618
        }
    }
}
